//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gy_User
    {
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Remark { get; set; }
        public bool StopFlag { get; set; }
        public bool FixedFlag { get; set; }
        public string TaxTypeCode { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
    }
}
